package com.servlet.api;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.apiKeys.APIKey;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.java.mapping.CityMapper;
import com.servlet.api.beans.FlightOffer;
import com.servlet.api.beans.SearchFlight;


@WebServlet("/flightSearch.do")
public class FlightSearchController extends HttpServlet {
	private static final long serialVersionUID = 1L;
//	private static final String FLIGHT_SEARCH_URL = "https://test.api.amadeus.com/v2/shopping/flight-offers";
//	private static String accessToken;
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		System.out.println("doget");
		//accessToken = APIKey.getAmaedusAccessToken();
		
		HttpSession session = request.getSession();
		
		String originLocationCode = request.getParameter("originLocationCode");
		String destinationLocationCode = request.getParameter("destinationLocationCode");
		String departureDate = request.getParameter("departureDate");
		String returnDate = request.getParameter("returnDate");
		String adults = request.getParameter("adults");
		String children = request.getParameter("children");
		String travelClass = request.getParameter("travelClass");
		
		SearchFlight searchInfo = new SearchFlight();
		searchInfo.setOriginLocationCode(CityMapper.getAirportCode(originLocationCode));
		searchInfo.setDestinationLocationCode(CityMapper.getAirportCode(destinationLocationCode));
		searchInfo.setDepartureDate(departureDate);
		searchInfo.setReturnDate(returnDate);
		searchInfo.setAdults(adults);
		searchInfo.setChildren(children);
		searchInfo.setTravelClass(travelClass);
		
		session.setAttribute("searchInfo", searchInfo);
		
		try {
//			URL url = new URL(FLIGHT_SEARCH_URL + searchInfo.toString());
//			HttpURLConnection connection = (HttpURLConnection) url.openConnection();
//			connection.setRequestMethod("GET");
//			connection.setRequestProperty("Authorization", "Bearer " + accessToken);
//			
//			BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
			// 멀티스레드에선 StringBuffer
//			StringBuilder resp = new StringBuilder();
//			String line;
//			while ((line = reader.readLine()) != null) {
//				resp.append(line);
//			}
//			reader.close();
	
			// api 미사용 용
			String resp = "{\r\n"
					+ "  \"meta\": {\r\n"
					+ "    \"count\": 5,\r\n"
					+ "    \"links\": {\r\n"
					+ "      \"self\": \"https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=ICN&destinationLocationCode=HND&departureDate=2023-12-22&returnDate=2023-12-25&adults=1&travelClass=ECONOMY&nonStop=true&currencyCode=KRW&max=250\"\r\n"
					+ "    }\r\n"
					+ "  },\r\n"
					+ "  \"data\": [\r\n"
					+ "    {\r\n"
					+ "      \"type\": \"flight-offer\",\r\n"
					+ "      \"id\": \"1\",\r\n"
					+ "      \"source\": \"GDS\",\r\n"
					+ "      \"instantTicketingRequired\": false,\r\n"
					+ "      \"nonHomogeneous\": false,\r\n"
					+ "      \"oneWay\": false,\r\n"
					+ "      \"lastTicketingDate\": \"2023-12-22\",\r\n"
					+ "      \"lastTicketingDateTime\": \"2023-12-22\",\r\n"
					+ "      \"numberOfBookableSeats\": 9,\r\n"
					+ "      \"itineraries\": [\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H10M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-22T20:40:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-22T22:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"KE\",\r\n"
					+ "              \"number\": \"719\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H10M\",\r\n"
					+ "              \"id\": \"1\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H50M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-25T02:00:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-25T04:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"KE\",\r\n"
					+ "              \"number\": \"720\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H50M\",\r\n"
					+ "              \"id\": \"5\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ],\r\n"
					+ "      \"price\": {\r\n"
					+ "        \"currency\": \"KRW\",\r\n"
					+ "        \"total\": \"746000.00\",\r\n"
					+ "        \"base\": \"605000.00\",\r\n"
					+ "        \"fees\": [\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"SUPPLIER\"\r\n"
					+ "          },\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"TICKETING\"\r\n"
					+ "          }\r\n"
					+ "        ],\r\n"
					+ "        \"grandTotal\": \"746000.00\"\r\n"
					+ "      },\r\n"
					+ "      \"pricingOptions\": {\r\n"
					+ "        \"fareType\": [\r\n"
					+ "          \"PUBLISHED\"\r\n"
					+ "        ],\r\n"
					+ "        \"includedCheckedBagsOnly\": true\r\n"
					+ "      },\r\n"
					+ "      \"validatingAirlineCodes\": [\r\n"
					+ "        \"KE\"\r\n"
					+ "      ],\r\n"
					+ "      \"travelerPricings\": [\r\n"
					+ "        {\r\n"
					+ "          \"travelerId\": \"1\",\r\n"
					+ "          \"fareOption\": \"STANDARD\",\r\n"
					+ "          \"travelerType\": \"ADULT\",\r\n"
					+ "          \"price\": {\r\n"
					+ "            \"currency\": \"KRW\",\r\n"
					+ "            \"total\": \"746000.00\",\r\n"
					+ "            \"base\": \"605000.00\"\r\n"
					+ "          },\r\n"
					+ "          \"fareDetailsBySegment\": [\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"1\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"MHE0ZRKB\",\r\n"
					+ "              \"class\": \"M\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 1\r\n"
					+ "              }\r\n"
					+ "            },\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"5\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"SHE0ZRKB\",\r\n"
					+ "              \"class\": \"S\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 1\r\n"
					+ "              }\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ]\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"type\": \"flight-offer\",\r\n"
					+ "      \"id\": \"2\",\r\n"
					+ "      \"source\": \"GDS\",\r\n"
					+ "      \"instantTicketingRequired\": false,\r\n"
					+ "      \"nonHomogeneous\": false,\r\n"
					+ "      \"oneWay\": false,\r\n"
					+ "      \"lastTicketingDate\": \"2023-12-11\",\r\n"
					+ "      \"lastTicketingDateTime\": \"2023-12-11\",\r\n"
					+ "      \"numberOfBookableSeats\": 9,\r\n"
					+ "      \"itineraries\": [\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H10M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-22T20:40:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-22T22:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"JL\",\r\n"
					+ "              \"number\": \"5256\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H10M\",\r\n"
					+ "              \"id\": \"2\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H50M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-25T02:00:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-25T04:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"JL\",\r\n"
					+ "              \"number\": \"5257\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H50M\",\r\n"
					+ "              \"id\": \"6\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ],\r\n"
					+ "      \"price\": {\r\n"
					+ "        \"currency\": \"KRW\",\r\n"
					+ "        \"total\": \"775900.00\",\r\n"
					+ "        \"base\": \"669900.00\",\r\n"
					+ "        \"fees\": [\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"SUPPLIER\"\r\n"
					+ "          },\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"TICKETING\"\r\n"
					+ "          }\r\n"
					+ "        ],\r\n"
					+ "        \"grandTotal\": \"775900.00\"\r\n"
					+ "      },\r\n"
					+ "      \"pricingOptions\": {\r\n"
					+ "        \"fareType\": [\r\n"
					+ "          \"PUBLISHED\"\r\n"
					+ "        ],\r\n"
					+ "        \"includedCheckedBagsOnly\": true\r\n"
					+ "      },\r\n"
					+ "      \"validatingAirlineCodes\": [\r\n"
					+ "        \"JL\"\r\n"
					+ "      ],\r\n"
					+ "      \"travelerPricings\": [\r\n"
					+ "        {\r\n"
					+ "          \"travelerId\": \"1\",\r\n"
					+ "          \"fareOption\": \"STANDARD\",\r\n"
					+ "          \"travelerType\": \"ADULT\",\r\n"
					+ "          \"price\": {\r\n"
					+ "            \"currency\": \"KRW\",\r\n"
					+ "            \"total\": \"775900.00\",\r\n"
					+ "            \"base\": \"669900.00\"\r\n"
					+ "          },\r\n"
					+ "          \"fareDetailsBySegment\": [\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"2\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YNN0NG4A\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            },\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"6\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YNN0NG4A\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ]\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"type\": \"flight-offer\",\r\n"
					+ "      \"id\": \"3\",\r\n"
					+ "      \"source\": \"GDS\",\r\n"
					+ "      \"instantTicketingRequired\": false,\r\n"
					+ "      \"nonHomogeneous\": false,\r\n"
					+ "      \"oneWay\": false,\r\n"
					+ "      \"lastTicketingDate\": \"2023-12-11\",\r\n"
					+ "      \"lastTicketingDateTime\": \"2023-12-11\",\r\n"
					+ "      \"numberOfBookableSeats\": 9,\r\n"
					+ "      \"itineraries\": [\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H10M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-22T20:40:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-22T22:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"JL\",\r\n"
					+ "              \"number\": \"5256\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H10M\",\r\n"
					+ "              \"id\": \"2\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H35M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-25T06:10:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"1\",\r\n"
					+ "                \"at\": \"2023-12-25T08:45:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"NH\",\r\n"
					+ "              \"number\": \"6895\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"333\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"OZ\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H35M\",\r\n"
					+ "              \"id\": \"4\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ],\r\n"
					+ "      \"price\": {\r\n"
					+ "        \"currency\": \"KRW\",\r\n"
					+ "        \"total\": \"776600.00\",\r\n"
					+ "        \"base\": \"669900.00\",\r\n"
					+ "        \"fees\": [\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"SUPPLIER\"\r\n"
					+ "          },\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"TICKETING\"\r\n"
					+ "          }\r\n"
					+ "        ],\r\n"
					+ "        \"grandTotal\": \"776600.00\"\r\n"
					+ "      },\r\n"
					+ "      \"pricingOptions\": {\r\n"
					+ "        \"fareType\": [\r\n"
					+ "          \"PUBLISHED\"\r\n"
					+ "        ],\r\n"
					+ "        \"includedCheckedBagsOnly\": true\r\n"
					+ "      },\r\n"
					+ "      \"validatingAirlineCodes\": [\r\n"
					+ "        \"JL\"\r\n"
					+ "      ],\r\n"
					+ "      \"travelerPricings\": [\r\n"
					+ "        {\r\n"
					+ "          \"travelerId\": \"1\",\r\n"
					+ "          \"fareOption\": \"STANDARD\",\r\n"
					+ "          \"travelerType\": \"ADULT\",\r\n"
					+ "          \"price\": {\r\n"
					+ "            \"currency\": \"KRW\",\r\n"
					+ "            \"total\": \"776600.00\",\r\n"
					+ "            \"base\": \"669900.00\"\r\n"
					+ "          },\r\n"
					+ "          \"fareDetailsBySegment\": [\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"2\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YNN0NG4A\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            },\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"4\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YFA0TD0Y\",\r\n"
					+ "              \"brandedFare\": \"ECOFULFLX\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ]\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"type\": \"flight-offer\",\r\n"
					+ "      \"id\": \"4\",\r\n"
					+ "      \"source\": \"GDS\",\r\n"
					+ "      \"instantTicketingRequired\": false,\r\n"
					+ "      \"nonHomogeneous\": false,\r\n"
					+ "      \"oneWay\": false,\r\n"
					+ "      \"lastTicketingDate\": \"2023-12-11\",\r\n"
					+ "      \"lastTicketingDateTime\": \"2023-12-11\",\r\n"
					+ "      \"numberOfBookableSeats\": 9,\r\n"
					+ "      \"itineraries\": [\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H20M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"1\",\r\n"
					+ "                \"at\": \"2023-12-22T21:10:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-22T23:30:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"NH\",\r\n"
					+ "              \"number\": \"6896\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"333\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"OZ\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H20M\",\r\n"
					+ "              \"id\": \"3\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H50M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-25T02:00:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"2\",\r\n"
					+ "                \"at\": \"2023-12-25T04:50:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"JL\",\r\n"
					+ "              \"number\": \"5257\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"32Q\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"KE\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H50M\",\r\n"
					+ "              \"id\": \"6\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ],\r\n"
					+ "      \"price\": {\r\n"
					+ "        \"currency\": \"KRW\",\r\n"
					+ "        \"total\": \"776600.00\",\r\n"
					+ "        \"base\": \"669900.00\",\r\n"
					+ "        \"fees\": [\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"SUPPLIER\"\r\n"
					+ "          },\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"TICKETING\"\r\n"
					+ "          }\r\n"
					+ "        ],\r\n"
					+ "        \"grandTotal\": \"776600.00\"\r\n"
					+ "      },\r\n"
					+ "      \"pricingOptions\": {\r\n"
					+ "        \"fareType\": [\r\n"
					+ "          \"PUBLISHED\"\r\n"
					+ "        ],\r\n"
					+ "        \"includedCheckedBagsOnly\": true\r\n"
					+ "      },\r\n"
					+ "      \"validatingAirlineCodes\": [\r\n"
					+ "        \"NH\"\r\n"
					+ "      ],\r\n"
					+ "      \"travelerPricings\": [\r\n"
					+ "        {\r\n"
					+ "          \"travelerId\": \"1\",\r\n"
					+ "          \"fareOption\": \"STANDARD\",\r\n"
					+ "          \"travelerType\": \"ADULT\",\r\n"
					+ "          \"price\": {\r\n"
					+ "            \"currency\": \"KRW\",\r\n"
					+ "            \"total\": \"776600.00\",\r\n"
					+ "            \"base\": \"669900.00\"\r\n"
					+ "          },\r\n"
					+ "          \"fareDetailsBySegment\": [\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"3\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YFA0TD0Y\",\r\n"
					+ "              \"brandedFare\": \"ECOFULFLX\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            },\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"6\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YNN0NG4A\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ]\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"type\": \"flight-offer\",\r\n"
					+ "      \"id\": \"5\",\r\n"
					+ "      \"source\": \"GDS\",\r\n"
					+ "      \"instantTicketingRequired\": false,\r\n"
					+ "      \"nonHomogeneous\": false,\r\n"
					+ "      \"oneWay\": false,\r\n"
					+ "      \"lastTicketingDate\": \"2023-12-22\",\r\n"
					+ "      \"lastTicketingDateTime\": \"2023-12-22\",\r\n"
					+ "      \"numberOfBookableSeats\": 9,\r\n"
					+ "      \"itineraries\": [\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H20M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"1\",\r\n"
					+ "                \"at\": \"2023-12-22T21:10:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-22T23:30:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"NH\",\r\n"
					+ "              \"number\": \"6896\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"333\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"OZ\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H20M\",\r\n"
					+ "              \"id\": \"3\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        },\r\n"
					+ "        {\r\n"
					+ "          \"duration\": \"PT2H35M\",\r\n"
					+ "          \"segments\": [\r\n"
					+ "            {\r\n"
					+ "              \"departure\": {\r\n"
					+ "                \"iataCode\": \"HND\",\r\n"
					+ "                \"terminal\": \"3\",\r\n"
					+ "                \"at\": \"2023-12-25T06:10:00\"\r\n"
					+ "              },\r\n"
					+ "              \"arrival\": {\r\n"
					+ "                \"iataCode\": \"ICN\",\r\n"
					+ "                \"terminal\": \"1\",\r\n"
					+ "                \"at\": \"2023-12-25T08:45:00\"\r\n"
					+ "              },\r\n"
					+ "              \"carrierCode\": \"NH\",\r\n"
					+ "              \"number\": \"6895\",\r\n"
					+ "              \"aircraft\": {\r\n"
					+ "                \"code\": \"333\"\r\n"
					+ "              },\r\n"
					+ "              \"operating\": {\r\n"
					+ "                \"carrierCode\": \"OZ\"\r\n"
					+ "              },\r\n"
					+ "              \"duration\": \"PT2H35M\",\r\n"
					+ "              \"id\": \"4\",\r\n"
					+ "              \"numberOfStops\": 0,\r\n"
					+ "              \"blacklistedInEU\": false\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ],\r\n"
					+ "      \"price\": {\r\n"
					+ "        \"currency\": \"KRW\",\r\n"
					+ "        \"total\": \"777300.00\",\r\n"
					+ "        \"base\": \"669900.00\",\r\n"
					+ "        \"fees\": [\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"SUPPLIER\"\r\n"
					+ "          },\r\n"
					+ "          {\r\n"
					+ "            \"amount\": \"0.00\",\r\n"
					+ "            \"type\": \"TICKETING\"\r\n"
					+ "          }\r\n"
					+ "        ],\r\n"
					+ "        \"grandTotal\": \"777300.00\"\r\n"
					+ "      },\r\n"
					+ "      \"pricingOptions\": {\r\n"
					+ "        \"fareType\": [\r\n"
					+ "          \"PUBLISHED\"\r\n"
					+ "        ],\r\n"
					+ "        \"includedCheckedBagsOnly\": true\r\n"
					+ "      },\r\n"
					+ "      \"validatingAirlineCodes\": [\r\n"
					+ "        \"NH\"\r\n"
					+ "      ],\r\n"
					+ "      \"travelerPricings\": [\r\n"
					+ "        {\r\n"
					+ "          \"travelerId\": \"1\",\r\n"
					+ "          \"fareOption\": \"STANDARD\",\r\n"
					+ "          \"travelerType\": \"ADULT\",\r\n"
					+ "          \"price\": {\r\n"
					+ "            \"currency\": \"KRW\",\r\n"
					+ "            \"total\": \"777300.00\",\r\n"
					+ "            \"base\": \"669900.00\"\r\n"
					+ "          },\r\n"
					+ "          \"fareDetailsBySegment\": [\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"3\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YFA0TD0Y\",\r\n"
					+ "              \"brandedFare\": \"ECOFULFLX\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            },\r\n"
					+ "            {\r\n"
					+ "              \"segmentId\": \"4\",\r\n"
					+ "              \"cabin\": \"ECONOMY\",\r\n"
					+ "              \"fareBasis\": \"YFA0TD0Y\",\r\n"
					+ "              \"brandedFare\": \"ECOFULFLX\",\r\n"
					+ "              \"class\": \"Y\",\r\n"
					+ "              \"includedCheckedBags\": {\r\n"
					+ "                \"quantity\": 2\r\n"
					+ "              }\r\n"
					+ "            }\r\n"
					+ "          ]\r\n"
					+ "        }\r\n"
					+ "      ]\r\n"
					+ "    }\r\n"
					+ "  ],\r\n"
					+ "  \"dictionaries\": {\r\n"
					+ "    \"locations\": {\r\n"
					+ "      \"ICN\": {\r\n"
					+ "        \"cityCode\": \"SEL\",\r\n"
					+ "        \"countryCode\": \"KR\"\r\n"
					+ "      },\r\n"
					+ "      \"HND\": {\r\n"
					+ "        \"cityCode\": \"TYO\",\r\n"
					+ "        \"countryCode\": \"JP\"\r\n"
					+ "      }\r\n"
					+ "    },\r\n"
					+ "    \"aircraft\": {\r\n"
					+ "      \"333\": \"AIRBUS A330-300\",\r\n"
					+ "      \"32Q\": \"AIRBUS A321NEO\"\r\n"
					+ "    },\r\n"
					+ "    \"currencies\": {\r\n"
					+ "      \"KRW\": \"S.KOREAN WON\"\r\n"
					+ "    },\r\n"
					+ "    \"carriers\": {\r\n"
					+ "      \"JL\": \"JAPAN AIRLINES\",\r\n"
					+ "      \"KE\": \"KOREAN AIR\",\r\n"
					+ "      \"NH\": \"ALL NIPPON AIRWAYS\",\r\n"
					+ "      \"OZ\": \"ASIANA AIRLINES\"\r\n"
					+ "    }\r\n"
					+ "  }\r\n"
					+ "}";
			// JSON 파싱
			ObjectMapper objectMapper = new ObjectMapper();
			FlightOffer offers = objectMapper.readValue(resp.toString(), FlightOffer.class);

			session.setAttribute("offers", offers);
			response.sendRedirect("flightSearch.jsp");
			
			
			
		}catch (IOException e) {
			e.printStackTrace();
		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
	}

}
